import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import memberAuthRouter from "./member-auth";
import usersRouter from "./users";
import membersRouter from "./members";
import virtualAccountsRouter from "./virtual_accounts";
import withdrawalsRouter from "./withdrawals";
import transactionsRouter from "./transactions";
import balancesRouter from "./balances";
import feesRouter from "./fees";
import statisticsRouter from "./statistics";
import noticesRouter from "./notices";
import otpRouter from "./otp";
import settlementsRouter from "./settlements";
import merchantsRouter from "./merchants";
import kpPayWebhooksRouter from "./kp-pay-webhooks";
import externalV1Router from "./external-v1";
import partnerRouter from "./partner-v4";
import kpPayVirtualAccountsRouter from "./kp-pay-virtual-accounts";
import platformOpsRouter from "./platform-ops";
const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(memberAuthRouter);
router.use(usersRouter);
router.use(membersRouter);
router.use(virtualAccountsRouter);
router.use(withdrawalsRouter);
router.use(transactionsRouter);
router.use(balancesRouter);
router.use(feesRouter);
router.use(statisticsRouter);
router.use(noticesRouter);
router.use(otpRouter);
router.use(settlementsRouter);
router.use(merchantsRouter);
router.use(platformOpsRouter);
router.use(kpPayWebhooksRouter);
router.use(externalV1Router);
router.use(partnerRouter);
router.use(kpPayVirtualAccountsRouter);

export default router;
