import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import memberAuthRouter from "./member-auth";
import memberRegistrationRouter from "./member-registration";
import usersRouter from "./users";
import membersRouter from "./members";
import virtualAccountsRouter from "./virtual_accounts";
import withdrawalsRouter from "./withdrawals";
import transactionsRouter from "./transactions";
import balancesRouter from "./balances";
import feesRouter from "./fees";
import statisticsRouter from "./statistics";
import noticesRouter from "./notices";
import otpRouter from "./otp";
import settlementsRouter from "./settlements";
import todopayRouter from "./todopay";
import internalFeesRouter from "./internal-fees";
import integrationMappingsRouter from "./integration-mappings";
const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(memberAuthRouter);
router.use(memberRegistrationRouter);
router.use(usersRouter);
router.use(membersRouter);
router.use(virtualAccountsRouter);
router.use(withdrawalsRouter);
router.use(transactionsRouter);
router.use(balancesRouter);
router.use(feesRouter);
router.use(statisticsRouter);
router.use(noticesRouter);
router.use(otpRouter);
router.use(settlementsRouter);
router.use(todopayRouter);
router.use(internalFeesRouter);
router.use(integrationMappingsRouter);

export default router;
