kind = "web"
previewPath = "/"
title = "TodoPay"
version = "1.0.0"
id = "artifacts/todopay"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 21259

[services.development]
run = "pnpm --filter @workspace/todopay run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/todopay", "run", "build" ]
publicDir = "artifacts/todopay/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "21259"
BASE_PATH = "/"
